// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZyWicBZikBQQcwEMYoPnDydnmoJuLv_A',
    appId: '1:561681764560:web:ec258c228c53b0d7174ed5',
    messagingSenderId: '561681764560',
    projectId: 'pushnotificationsforhawir',
    authDomain: 'pushnotificationsforhawir.firebaseapp.com',
    storageBucket: 'pushnotificationsforhawir.firebasestorage.app',
    measurementId: 'G-QM7F10SK3P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBN5uYXSGgcH9eiype8TSt0BzlhKk6qhb0',
    appId: '1:561681764560:android:562a937b9c696575174ed5',
    messagingSenderId: '561681764560',
    projectId: 'pushnotificationsforhawir',
    storageBucket: 'pushnotificationsforhawir.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABIcSGUcfxhs10kF2Pl0Zig-bYNR1HByg',
    appId: '1:561681764560:ios:0f34b668fd584b96174ed5',
    messagingSenderId: '561681764560',
    projectId: 'pushnotificationsforhawir',
    storageBucket: 'pushnotificationsforhawir.firebasestorage.app',
    iosBundleId: 'com.example.travellerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyABIcSGUcfxhs10kF2Pl0Zig-bYNR1HByg',
    appId: '1:561681764560:ios:0f34b668fd584b96174ed5',
    messagingSenderId: '561681764560',
    projectId: 'pushnotificationsforhawir',
    storageBucket: 'pushnotificationsforhawir.firebasestorage.app',
    iosBundleId: 'com.example.travellerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAZyWicBZikBQQcwEMYoPnDydnmoJuLv_A',
    appId: '1:561681764560:web:bafc34865260a4aa174ed5',
    messagingSenderId: '561681764560',
    projectId: 'pushnotificationsforhawir',
    authDomain: 'pushnotificationsforhawir.firebaseapp.com',
    storageBucket: 'pushnotificationsforhawir.firebasestorage.app',
    measurementId: 'G-4285E22E4E',
  );

}